# Generated by Django 3.1.7 on 2021-04-09 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('level', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('course_id', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('lecturer_id', models.CharField(max_length=130)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('subject_id', models.CharField(max_length=130)),
                ('classroom_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.classroom', verbose_name='classroom related')),
                ('lecturer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.lecturer', verbose_name='classroom related')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('student_id', models.CharField(max_length=130)),
                ('course_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.course', verbose_name='course related')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=130)),
                ('time', models.CharField(max_length=130)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.student', verbose_name='student related')),
            ],
        ),
    ]
